version: '3.8'

services:
  app:
    image: service-user-investor
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - DB_USER=root
      - DB_PASS=
      - DB_NAME=service_user_investor
      - DB_PORT=3306
      - INSTANCE_HOST=127.0.0.1
      - PORT=8082
  